### ISSUE TITLE
Getting error when sending a JSON serialized object

### ISSUE THREAD

**Issue by zerocarbthirty** [sypbiz/SockJS.NET#2] opened 2019-11-24 21:01 UTC
Hello, a 3rd party API uses SockJS and I built a javascript application that connects to it just fine. I am trying to use your client library to send JSON (using the Send method) and it seems to be having a really hard time with that.

I've tried using JsonSerialize on an object, I've tried manually building the JSON string, i've tried everything. Are you aware of any problem with your library being able to send JSON?

**Comment by doronguttman** [comment] 2019-11-25 13:17
@zerocarbthirty can you provide code example and details of the error you're getting?

**Comment by zerocarbthirty** [comment] 2019-11-25 14:04
Hi, sure I can do that when I get back to the source later today. In general the remote host just sends back a 500 server error when I use .Send to send a big blob of JSON (which is an object serialized by Newtonsoft Json) I was just wondering if maybe .Send was trying to encode or chunk the JSON in a way that is causing the message to get to the remote server incorrectly. I wish I could get a better description of why the remote host was returning 500 but yeah good luck with that.

`<script>
var chat = new SockJS('https://chatws11.hostremoved.com/ws');
var obj = {
    'method' : 'connect',
    'data' : {
        'user'  : 'removed',
        'password' : '{"username":"removed","org":"A","expire":1574692290,"sig":"95ca601a5d99c52855a15e23e2c5274065db41fe0f21a1f3953c5e285f166f3b","room":"removed"}',
        'room' : 'removed',
        'room_password' : 'removed'
    }
};
var two = {
    'method' : 'joinRoom',
    'data' : {
        'room' : 'removed'
    }
};
var connect = JSON.stringify(obj);
var join = JSON.stringify(two);
chat.onopen = function() {
     console.log('open');
     chat.send(connect);
     chat.send(join); 
};
</script>

Above is the javascript I am trying to convert over to C#`

**Comment by zerocarbthirty** [comment] 2019-11-25 21:13
``var ozz = new { 
                            method = "connect", 
                            data = new  { 
                                user = chat_username, 
                                password = chat_password,
                                room = room,
                                room_password = room_pass
                            } 
                            };
                var ozzz = new
                {
                    method = "joinRoom",
                    data = new
                    {
                        room = room
                    }
                };
                string JSONConn = JsonConvert.SerializeObject(ozz).ToString();
                string JSONJoin = JsonConvert.SerializeObject(ozzz);
                SockJS.SetLogger(new ConsoleLogger()); // sets the global logger
                var sockJs = new SockJS(wschat_host);
                sockJs.AddEventListener("open", (sender, e) =>
                {
                    sockJs.Send(JSONConn);
                });

results in:

2019-11-25T16:08:35 [DBG] CreateAjaxSender: Create ajax sender https://chatws3.hostname.com:443/ws/991/dcfebhce ["{"method":"connect","data":{"user":"__anonymous__M2I4uL","password":"{\"username\":\"__anonymous__M2I4uL\",\"org\":\"A\",\"expire\":1574717914,\"sig\":\"1e6faa639f7e65db92b725d13fbe87b0f5a5010c366276528fcf734fe87b2d22\",\"room\":\"room\"}","room":"rm","room_password":"redacted"}}"]
2019-11-25T16:08:35 [DBG] XhrDriver: POST https://chatws3.hostname.com:443/ws/991/dcfebhce/xhr_send ["{"method":"connect","data":{"user":"__anonymous__M2I4uL","password":"{\"username\":\"__anonymous__M2I4uL\",\"org\":\"A\",\"expire\":1574717914,\"sig\":\"1e6faa639f7e65db92b725d13fbe87b0f5a5010c366276528fcf734fe87b2d22\",\"room\":\"room\"}","room":"rm","room_password":"redacted"}}"]
2019-11-25T16:08:35 [DBG] XhrDriver: End
2019-11-25T16:08:35 [DBG] OnFinish: Finish 200 o

2019-11-25T16:08:35 [DBG] ChunkHandler: 200
2019-11-25T16:08:35 [DBG] OnFinish: Close network
2019-11-25T16:08:35 [DBG] OnClose: Close  network False
2019-11-25T16:08:35 [DBG] ScheduleReceiver
2019-11-25T16:08:35 [DBG] XhrReceiver: https://chatws3.hostname.com:443/ws/991/dcfebhce/xhr
2019-11-25T16:08:35 [DBG] XhrDriver: POST https://chatws3.hostname.com:443/ws/991/dcfebhce/xhr
2019-11-25T16:08:35 [DBG] Cleanup
2019-11-25T16:08:35 [DBG] XhrDriver: End
2019-11-25T16:08:35 [DBG] XhrDriver: Error System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at syp.biz.SockJS.NET.Client.Transports.Lib.Driver.XhrDriver.<>c.<.ctor>b__2_0(Task`1 t) in C:\Users\aweav\Downloads\SockJS.NET-master\SockJS.NET-master\syp.biz\SockJS.NET\syp.biz.SockJS.NET.Client\Transports\Lib\Driver\XhrDriver.cs:line 44
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
2019-11-25T16:08:35 [DBG] CreateAjaxSender: Finish 0
2019-11-25T16:08:35 [DBG] SendSchedule: Error System.Exception: http status 0
2019-11-25T16:08:35 [DBG] Close

**Comment by zerocarbthirty** [comment] 2019-11-25 22:47
Did some further testing, the test server also has a 500 when I send serialized JS to it.

i.e.  var sockJs = new SockJS("http://localhost:9999/echo");

SockJS v0.3.19 bound to "/echo"
GET /echo/info 2ms 200
GET /echo/777/edhggegg/websocket 2ms (unfinished)
connection websocket /echo/777/edhggegg/websocket c0fc55de-c6a4-4b4b-804e-47c894a86f75
POST /echo/777/bdhbcggb/xhr 1ms 200
connection xhr-polling /echo/777/bdhbcggb/xhr 0f955349-c668-4b9b-a878-e44b7b25f5ce
POST /echo/777/bdhbcggb/xhr_send 2ms 500
POST /echo/777/bdhbcggb/xhr 0ms (unfinished)
close

**Comment by zerocarbthirty** [comment] 2019-11-25 23:06
Did a little more fiddling. It seems like double quotes of any kind totally makes .Send unhappy:

sockJs.Send("{'ip':'8.8.8.8'}");

GET /echo/info 0ms 200
GET /echo/719/afhebcfg/websocket 0ms (unfinished)
connection websocket /echo/719/afhebcfg/websocket 2650c8cc-fced-4c87-87fa-037de2cacafb
POST /echo/719/eebfachd/xhr 1ms 200
connection xhr-polling /echo/719/eebfachd/xhr c548eeb4-8474-47f7-b5e7-a2a37040a512
data >>> {'ip':'8.8.8.8'}
data <<< {'ip':'8.8.8.8'}
POST /echo/719/eebfachd/xhr_send 3ms 204
POST /echo/719/eebfachd/xhr 0ms 200
POST /echo/719/eebfachd/xhr 0ms (unfinished)

sockJs.Send("{\"'ip':'8.8.8.8'}");

GET /echo/info 1ms 200
GET /echo/624/eedcfcfc/websocket 1ms (unfinished)
connection websocket /echo/624/eedcfcfc/websocket 5b3dc34e-959a-4e7c-9727-ecd6e9dbd792
POST /echo/624/fcedhdec/xhr 0ms 200
connection xhr-polling /echo/624/fcedhdec/xhr 5a3f677c-6df9-41ed-9573-4f2d5f429546
POST /echo/624/fcedhdec/xhr_send 2ms 500
POST /echo/624/fcedhdec/xhr 0ms (unfinished)

**Comment by zerocarbthirty** [comment] 2019-11-26 18:11
Hi there friend, I did some more testing, it looks like the only reason it works in SockJS is because it is double escaping quotes: 

This is what the string looks like after JSON.Stringify:

{"method":"joinRoom","data":{"room":"rm"}}

This is what SockJS actually sends (in chrome, anyway):

["{\"method\":\"joinRoom\",\"data\":{\"room\":\"rm\"}}"]:

I think this code is responsible for doing this in the SockJS client:

lib/main.js
`164 this._transport.send(escape.quote(data));`

So should I just double-escape everything before passing it to .Send or should we add a line to make sure that its double escaped?

**Comment by doronguttman** [comment] 2019-11-27 15:03
looking into it...

**Comment by doronguttman** [comment] 2019-11-27 20:42
@zerocarbthirty thank you for opening the issue and providing all the information (including a helpful pointer). I think the issue is [now resolved](https://github.com/sypbiz/SockJS.NET/commit/48ccd641f226a851d0c311d4c4b1433cd201db42). Please confirm

**Comment by zerocarbthirty** [comment] 2019-11-27 21:12
Yeah I just ended up using this: 

string other = HttpUtility.JavaScriptStringEncode(JsonConvert.SerializeObject(ozz));

as long as you are escaping quotes when Sending it should work.

Thanks.

**Comment by zerocarbthirty** [comment] 2019-11-27 23:03
Hey, I had one other really silly question is it possible to define the event handlers like this?

sockJs.OnMessage += onMessage;
In lieu of:
sockJs.AddEventListener("message" (sender, e) => .. );

??

**Comment by doronguttman** [comment] 2019-11-28 15:28
> Hey, I had one other really silly question is it possible to define the event handlers like this?
> 
> sockJs.OnMessage += onMessage;
> In lieu of:
> sockJs.AddEventListener("message" (sender, e) => .. );
> 
> ??

@zerocarbthirty 
I have opened another issue for this, see: https://github.com/sypbiz/SockJS.NET/issues/4

As for the current issue, can you please verify the updated code resolves the issue so it can be closed?

**Comment by dguttman-jacada** [comment] 2019-12-31 21:25
closing with no response

**Comment by doronguttman** [comment] 2019-12-31 21:26
closing with no reponse

**Closed by doronguttman** 2019-12-31 21:26 UTC
Labels: bug
